name: Generate Sitemap

on:
  push:
    branches:
      - main  # Change to "master" or "gh-pages" if your default branch uses that name
    paths:
      - '**.html'

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to pull git dates for lastmod

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://1v1lol-gg.github.io/
          include-pdf: false

      - name: Commit and Push Sitemap
        run: |
          if [[ `git status --porcelain sitemap.xml` ]]; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add sitemap.xml
            git commit -m "auto: update sitemap.xml"
            git push
          fi
